### ISSUE TITLE
Update for new GOG DB format

### ISSUE THREAD

**Issue by eniklas** [eniklas/gamatrix-gog#103]
It seems the GOG DB schema has changed and no longer has the `GameLinks` table. When it's run with a recent DB it crashes:

```Jan 10 21:36:16 batty 7a1519ef2b80[1868]: 2022-01-10 21:36:16 ERROR gamatrix Exception on /compare [GET]
Jan 10 21:36:16 batty 7a1519ef2b80[1868]: Traceback (most recent call last):
Jan 10 21:36:16 batty 7a1519ef2b80[1868]:   File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 2447, in wsgi_app
Jan 10 21:36:16 batty 7a1519ef2b80[1868]:     response = self.full_dispatch_request()
Jan 10 21:36:16 batty 7a1519ef2b80[1868]:   File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1952, in full_dispatch_request
Jan 10 21:36:16 batty 7a1519ef2b80[1868]:     rv = self.handle_user_exception(e)
Jan 10 21:36:16 batty 7a1519ef2b80[1868]:   File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1821, in handle_user_exception
Jan 10 21:36:16 batty 7a1519ef2b80[1868]:     reraise(exc_type, exc_value, tb)
Jan 10 21:36:16 batty 7a1519ef2b80[1868]:   File "/usr/local/lib/python3.9/site-packages/flask/_compat.py", line 39, in reraise
Jan 10 21:36:16 batty 7a1519ef2b80[1868]:     raise value
Jan 10 21:36:16 batty 7a1519ef2b80[1868]:   File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1950, in full_dispatch_request
Jan 10 21:36:16 batty 7a1519ef2b80[1868]:     rv = self.dispatch_request()
Jan 10 21:36:16 batty 7a1519ef2b80[1868]:   File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1936, in dispatch_request
Jan 10 21:36:16 batty 7a1519ef2b80[1868]:     return self.view_functions[rule.endpoint](**req.view_args)
Jan 10 21:36:16 batty 7a1519ef2b80[1868]:   File "/usr/src/app/./gamatrix.py", line 163, in compare_libraries
Jan 10 21:36:16 batty 7a1519ef2b80[1868]:     common_games = gog.get_common_games()
Jan 10 21:36:16 batty 7a1519ef2b80[1868]:   File "/usr/src/app/helpers/gogdb_helper.py", line 194, in get_common_games
Jan 10 21:36:16 batty 7a1519ef2b80[1868]:     owned_games = self.get_owned_games()
Jan 10 21:36:16 batty 7a1519ef2b80[1868]:   File "/usr/src/app/helpers/gogdb_helper.py", line 120, in get_owned_games
Jan 10 21:36:16 batty 7a1519ef2b80[1868]:     self.cursor.execute(query)
Jan 10 21:36:16 batty 7a1519ef2b80[1868]: sqlite3.OperationalError: no such table: GameLinks
```

I diffed the list of tables between an old and new DB, hoping they had just renamed it, but alas, it's more complicated than that. `GameLinks` is gone, and `OsCompatibilities` has been added, but is not the same data. The script needs to be updated to use the new schema.

**Comment by eniklas** [comment]
The project that I'd originally cribbed the queries from has [fixed the issue](https://github.com/AB1908/GOG-Galaxy-Export-Script/pull/53), so I made the [same change](https://github.com/eniklas/gamatrix/pull/104). Thanks @TheMelmacian!
