### ISSUE TITLE
Handle bad DB files

### ISSUE THREAD

**Issue by eniklas** [eniklas/gamatrix-gog#81]
I uploaded a new DB while I was doing a big file copy, which caused the DB copy to hang. I killed it, and it looked like the whole file was on disk, but when I made a request on the site it got a 500. The logs showed:
```
2021-03-23 05:05:08 ERROR gamatrix-gog Exception on /compare [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.9/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/src/app/./gamatrix-gog.py", line 157, in compare_libraries
    common_games = gog.get_common_games()
  File "/usr/src/app/helpers/gogdb_helper.py", line 184, in get_common_games
    userid = self.get_user()[0]
  File "/usr/src/app/helpers/gogdb_helper.py", line 59, in get_user
    user_query = self.cursor.execute("select * from Users")
sqlite3.DatabaseError: file is not a database
```
Handle that exception gracefully.

**Comment by eniklas** [comment]
The issue causing the corrupted DB uploads was due to us doing a `read` of the first 2048 bytes of the uploaded file to check that it's an sqlite file; the subsequent `save` would start where the read left off. This has been fixed in https://github.com/eniklas/gamatrix-gog/commit/1bfc2eaf53aa150e16f5820752f5abfe36438a53. Not going to handle that condition elsewhere since it's checked during upload, and if there's a bug in the upload as there was in this case, we want to know about it there.
